export default interface Lab {
  categorieStructure: string,
  codeUnite: string,
  dateCreation: Date,
  delegationRegionaleCode: Number,
  delegationRegionaleLibelle: string,
  dernierEtablissementRattachementDateFinValidite: Date,
  dernierEtablissementRattachementLibelle: string,
  derniereImplantationDelegationRegionaleCode: Number,
  derniereImplantationDelegationRegionaleLibelle: string,
  derniereImplantationEtablissement: {
    Voie: string,
    boitePostale: string,
    codePostalEtranger: string,
    communeEtrangere: string,
    communeFrancaise: {
      codePostal: string,
      commune: string,
      idReseda: string,
      libelleAcheminement: string,
      ligne5Hexaposte: string,
    },
    complementAdresse: string,
    courrielContactWeb: string,
    delegationRegionale: {
      code: string,
      idReseda: string,
      libelle: string,
    },
    departement: {
      code: string,
      idReseda: string,
      libelle: string,
    },
    etablissementImplantation: {
      code: string,
      idReseda: string,
      libelle: string,
    },
    idOldImplantation: string,
    infrastructure: {
      code: string,
      idReseda: string,
      libelle: string,
    },
    numOrdre: number
    numVoie: string,
    pays: {
      codeIso2: string,
      codeIso3: string,
      idReseda: string,
      libelle: string,
    },
    region : {
      code: string,
      idReseda: string,
      libelle: string,
    },
    sHON: number,
    site: {
      code: string,
      idReseda: string,
      libelle: string,
    },
    sncMere,
    surfaceUtile,
  },
  derniereImplantations: string,
  derniereImplantationsCodeEmplacement: number,
  derniereImplantationsCodeEmplacementLibelle: string,
  derniereImplantationsCodeStructure: string,
  derniereImplantationsCodeUnite: string,
  derniereImplantationsDateDebut: Date,
  derniereImplantationsDateFin: Date,
  derniereImplantationsInstitutRattachementLibelle: string,
  derniereImplantationsLibelle: string,
  effectifUnite: number,
  etatStructure: string,
  ezMetaDate: Date,
  idReseda: number,
  intituleUnite: string,
  numeroUnite: number,
  personnels: {
    code: string,
    libelle: string,
    total: number,
  },
  personnels_APPR: number,
  personnels_A_MODIFIER: number,
  personnels_CH: number,
  personnels_DOCT: number,
  personnels_ENS_CH: number,
  personnels_IT: number,
  personnels_POST_DOCT: number,
  personnels_STAG_ETUD: number,
  personnels_VACAT: number,
  sigleUnite: string,
  typeUniteCode: string,
  typeUniteLibelle: string,
}
